project:
  type: website
  output-dir: docs

website:
  title: "Stat 334 (Data Visualization) Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cecilyhansen
format:
  html:
    theme: minty
    css: styles.css

editor: visual

